/**
 * Country-name → flag-emoji helpers for the mobile UI.
 *
 * Metal Archives writes the band's country as a free-form English name (e.g.
 * "United States", "Norway"). We keep a small built-in name → ISO 3166-1
 * alpha-2 map covering the values MA actually emits, then convert the alpha-2
 * code into the regional-indicator emoji pair the OS renders as a flag.
 *
 * Alpha-2 codes already in the tag are passed through unchanged.
 */

const NAME_TO_ALPHA2: Record<string, string> = {
  afghanistan: 'AF',
  albania: 'AL',
  algeria: 'DZ',
  andorra: 'AD',
  angola: 'AO',
  argentina: 'AR',
  armenia: 'AM',
  australia: 'AU',
  austria: 'AT',
  azerbaijan: 'AZ',
  bahrain: 'BH',
  bangladesh: 'BD',
  belarus: 'BY',
  belgium: 'BE',
  bolivia: 'BO',
  'bosnia and herzegovina': 'BA',
  botswana: 'BW',
  brazil: 'BR',
  brunei: 'BN',
  bulgaria: 'BG',
  cambodia: 'KH',
  cameroon: 'CM',
  canada: 'CA',
  chile: 'CL',
  china: 'CN',
  colombia: 'CO',
  'costa rica': 'CR',
  croatia: 'HR',
  cuba: 'CU',
  cyprus: 'CY',
  'czech republic': 'CZ',
  czechia: 'CZ',
  denmark: 'DK',
  'dominican republic': 'DO',
  ecuador: 'EC',
  egypt: 'EG',
  'el salvador': 'SV',
  estonia: 'EE',
  ethiopia: 'ET',
  'faroe islands': 'FO',
  finland: 'FI',
  france: 'FR',
  georgia: 'GE',
  germany: 'DE',
  ghana: 'GH',
  greece: 'GR',
  greenland: 'GL',
  guatemala: 'GT',
  honduras: 'HN',
  'hong kong': 'HK',
  hungary: 'HU',
  iceland: 'IS',
  india: 'IN',
  indonesia: 'ID',
  iran: 'IR',
  iraq: 'IQ',
  ireland: 'IE',
  israel: 'IL',
  italy: 'IT',
  jamaica: 'JM',
  japan: 'JP',
  jordan: 'JO',
  kazakhstan: 'KZ',
  kenya: 'KE',
  kuwait: 'KW',
  kyrgyzstan: 'KG',
  laos: 'LA',
  latvia: 'LV',
  lebanon: 'LB',
  libya: 'LY',
  liechtenstein: 'LI',
  lithuania: 'LT',
  luxembourg: 'LU',
  macau: 'MO',
  'north macedonia': 'MK',
  macedonia: 'MK',
  madagascar: 'MG',
  malaysia: 'MY',
  maldives: 'MV',
  malta: 'MT',
  mexico: 'MX',
  moldova: 'MD',
  monaco: 'MC',
  mongolia: 'MN',
  montenegro: 'ME',
  morocco: 'MA',
  mozambique: 'MZ',
  myanmar: 'MM',
  nepal: 'NP',
  netherlands: 'NL',
  'new zealand': 'NZ',
  nicaragua: 'NI',
  nigeria: 'NG',
  'north korea': 'KP',
  norway: 'NO',
  oman: 'OM',
  pakistan: 'PK',
  palestine: 'PS',
  panama: 'PA',
  paraguay: 'PY',
  peru: 'PE',
  philippines: 'PH',
  poland: 'PL',
  portugal: 'PT',
  'puerto rico': 'PR',
  qatar: 'QA',
  romania: 'RO',
  russia: 'RU',
  'saudi arabia': 'SA',
  senegal: 'SN',
  serbia: 'RS',
  singapore: 'SG',
  slovakia: 'SK',
  slovenia: 'SI',
  'south africa': 'ZA',
  'south korea': 'KR',
  spain: 'ES',
  'sri lanka': 'LK',
  sudan: 'SD',
  sweden: 'SE',
  switzerland: 'CH',
  syria: 'SY',
  taiwan: 'TW',
  tajikistan: 'TJ',
  tanzania: 'TZ',
  thailand: 'TH',
  tunisia: 'TN',
  turkey: 'TR',
  turkmenistan: 'TM',
  uganda: 'UG',
  ukraine: 'UA',
  'united arab emirates': 'AE',
  'united kingdom': 'GB',
  uk: 'GB',
  'great britain': 'GB',
  england: 'GB',
  scotland: 'GB',
  wales: 'GB',
  'northern ireland': 'GB',
  'united states': 'US',
  'united states of america': 'US',
  usa: 'US',
  uruguay: 'UY',
  uzbekistan: 'UZ',
  venezuela: 'VE',
  vietnam: 'VN',
  yemen: 'YE',
  zimbabwe: 'ZW',
};

/** Convert a country name (or alpha-2 code) to its ISO alpha-2 code. */
export function toAlpha2(country: string | null | undefined): string | null {
  if (!country) return null;
  const trimmed = country.trim();
  if (!trimmed) return null;
  if (/^[A-Za-z]{2}$/.test(trimmed)) return trimmed.toUpperCase();
  return NAME_TO_ALPHA2[trimmed.toLowerCase()] ?? null;
}

/** Convert a country name (or alpha-2 code) to its regional-indicator flag emoji. */
export function toFlagEmoji(country: string | null | undefined): string | null {
  const code = toAlpha2(country);
  if (!code) return null;
  // Each ASCII letter maps to its regional indicator codepoint (U+1F1E6 + offset).
  const a = code.charCodeAt(0) - 'A'.charCodeAt(0);
  const b = code.charCodeAt(1) - 'A'.charCodeAt(0);
  if (a < 0 || a > 25 || b < 0 || b > 25) return null;
  return String.fromCodePoint(0x1f1e6 + a, 0x1f1e6 + b);
}
